version: 1.0.0.{build}

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  GENERATOR: Visual Studio 14 2015
  COMPILER_VERSION: 14

install:
  - cmd: pip install conan
  - cmd: cmake --help
  - cmd: npm install
  - cmd: npm test
